### ISSUE TITLE
我用第三方ui库会把ui库的样式搞乱！！

### ISSUE THREAD

**Issue by Niofh** [givebest/GB-respond#1]
我用了vue-mint UI库，引入你的js会把样式搞乱了

**Comment by givebest** [comment]
`REM` 是 `Root EM`，这个 `Root` 就是 `HTML` 的 `font-size`，页面其它基于 `REM` 单位的元素才会受影响（页面默认 `Root` 字体大小为： `<html style="font-size: 100px">`）
我看了 `https://github.com/ElemeFE/mint-ui/` 单位是 `px` 应该不受影响
